# The URL the site will be built for
base_url = "https://blog.eevans.xyz"

# The site title and description; used in feeds by default.
title = "Birdbrain Hours"
description = ""

theme = "PaperMod"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
highlight_theme = "gruvbox-dark"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

[extra]
[extra.papermod]
title = "Birdbrain Hours"
default_theme = "auto"
theme = "dark"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = false
show_code_copy_buttons = true
show_reading_time = false
show_word_count = false
show_post_nav_links = true
show_post_meta = false
default_toc_open = false
edit_post_url = "https://github.com/ethanavatar"
copyright = "© 2023 Ethan Evans"
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
]

home_title = "Birdbrain Hours"
home_content = ""
social_icons = [
    { url = "https://github.com/ethanavatar", title = "GitHub", icon = "github" },
]
